version: "3.8"

services:
  peaky-peek:
    build:
      context: .
      dockerfile: Dockerfile
    image: peaky-peek-server:latest
    container_name: peaky-peek
    ports:
      - "8000:8000"
    volumes:
      - ./traces:/app/traces
    restart: unless-stopped
