"""API configuration constants."""

# Session list limits
MAX_SESSIONS_PER_PAGE = 1000

# Event/trace limits
MAX_TRACES_PER_REQUEST = 10000
MAX_EVENTS_FOR_ANALYSIS = 1000

# Search limits
MAX_SEARCH_RESULTS = 500
MAX_SESSION_SEARCH_RESULTS = 100

# Alert limits
MAX_ALERTS_PER_REQUEST = 200

# Text field limits
MAX_QUERY_LENGTH = 256
MIN_SEARCH_QUERY_LENGTH = 2
MAX_FIX_NOTE_LENGTH = 2000
