"""Unified re-export of all API Pydantic schemas.

Schemas are organized by domain in sibling modules:
- schemas_core: sessions, events, checkpoints, traces, API keys
- schemas_alerts: anomaly alerts, alert policies, fix notes
- schemas_analysis: workflow, safety, redundancy, causal, drift, baseline

All names are re-exported here so existing imports from ``api.schemas``
continue to work without modification.
"""

from api.schemas_core import (  # noqa: F401
    AnalysisResponse,
    CheckpointDeltaSchema,
    CheckpointDeltasResponse,
    CheckpointListResponse,
    CheckpointSchema,
    CollapsedSegmentSchema,
    CreateKeyRequest,
    CreateKeyResponse,
    DecisionTreeResponse,
    DeleteResponse,
    HighlightSchema,
    KeyListItem,
    LiveSummaryResponse,
    ReplayResponse,
    RestoreRequest,
    RestoreResponse,
    SessionDetailResponse,
    SessionListResponse,
    SessionSchema,
    SessionUpdateRequest,
    TraceBundleResponse,
    TraceEventSchema,
    TraceListResponse,
    TraceSearchResponse,
)
from api.schemas_alerts import (  # noqa: F401
    AlertBulkUpdate,
    AlertFilters,
    AlertListFilteredResponse,
    AlertPolicyCreate,
    AlertPolicyListResponse,
    AlertPolicySchema,
    AlertPolicyUpdate,
    AlertSeverityCount,
    AlertStatusUpdate,
    AlertSummarySchema,
    AlertTrendingPointSchema,
    AlertTrendingSchema,
    AnomalyAlertListResponse,
    AnomalyAlertSchema,
    FixNoteRequest,
    FixNoteResponse,
)
from api.schemas_analysis import (  # noqa: F401
    AgentBaselineSchema,
    CausalAnalysisResponse,
    CausalEdgeSchema,
    CausalGraphSchema,
    CausalNodeSchema,
    CriticalPathAnalysis,
    CriticalPathEvent,
    DriftAlertSchema,
    DriftResponseSchema,
    RedundancyAnalysisResponse,
    RedundancyScoreSchema,
    RedundancySummarySchema,
    SafetyAlertSchema,
    SafetyAnalysisResponse,
    SafetyScoreSchema,
    SessionSafetyReportSchema,
    SimilarFailureSchema,
    SimilarFailuresResponse,
    WeakPoint,
    WorkflowEdgeSchema,
    WorkflowGraphResponse,
    WorkflowGraphSchema,
    WorkflowNodeSchema,
)

__all__ = [
    # Core schemas
    "SessionSchema",
    "TraceEventSchema",
    "CheckpointSchema",
    "SessionListResponse",
    "SessionDetailResponse",
    "SessionUpdateRequest",
    "TraceListResponse",
    "DecisionTreeResponse",
    "TraceBundleResponse",
    "ReplayResponse",
    "AnalysisResponse",
    "LiveSummaryResponse",
    "TraceSearchResponse",
    "CheckpointListResponse",
    "CheckpointDeltaSchema",
    "CheckpointDeltasResponse",
    "RestoreRequest",
    "RestoreResponse",
    "DeleteResponse",
    "HighlightSchema",
    "CollapsedSegmentSchema",
    "CreateKeyRequest",
    "CreateKeyResponse",
    "KeyListItem",
    # Alert schemas
    "AnomalyAlertSchema",
    "AnomalyAlertListResponse",
    "AlertStatusUpdate",
    "AlertBulkUpdate",
    "AlertFilters",
    "AlertSeverityCount",
    "AlertSummarySchema",
    "AlertTrendingPointSchema",
    "AlertTrendingSchema",
    "AlertListFilteredResponse",
    "FixNoteRequest",
    "FixNoteResponse",
    "AlertPolicyCreate",
    "AlertPolicyUpdate",
    "AlertPolicySchema",
    "AlertPolicyListResponse",
    # Analysis schemas
    "WorkflowNodeSchema",
    "WorkflowEdgeSchema",
    "WorkflowGraphSchema",
    "WorkflowGraphResponse",
    "SafetyScoreSchema",
    "SafetyAlertSchema",
    "SessionSafetyReportSchema",
    "SafetyAnalysisResponse",
    "RedundancyScoreSchema",
    "RedundancySummarySchema",
    "RedundancyAnalysisResponse",
    "CausalNodeSchema",
    "CausalEdgeSchema",
    "CausalGraphSchema",
    "CriticalPathEvent",
    "WeakPoint",
    "CriticalPathAnalysis",
    "CausalAnalysisResponse",
    "AgentBaselineSchema",
    "DriftAlertSchema",
    "DriftResponseSchema",
    "SimilarFailureSchema",
    "SimilarFailuresResponse",
]
